portfolio2024/portfolio/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "portfolio"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("detail/<int:pk>", views.DetailView.as_view(), name="detail"),
    path(
        "login/", auth_views.LoginView.as_view(template_name="login.html"), name="login"
    ),
    path("post/<int:pk>", views.PostView.as_view(), name="post"),
]

portfolio2024/portfolio2024/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('portfolio.urls')),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

portfolio2024/portfolio/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

def user_path(instance, filename):
    return f'photos/{instance.student.student_no}'

# Create your models here.
class Student(AbstractUser):
    # 学生番号　2447000 student_no
    student_no = models.IntegerField(
        verbose_name="学生番号",
        primary_key=True
    )
    # 氏名　下道 俊樹 student_name
    username = models.CharField(
        verbose_name="学生氏名",
        max_length=20,
        blank=True
    )
    
    USERNAME_FIELD = "student_no"
    REQUIRED_FIELDS = ['username']
    
    def __str__(self):
        return self.username

class System(models.Model):
    student = models.OneToOneField(
        Student,
        verbose_name="学生",
        on_delete=models.CASCADE,
        primary_key=True
    )
    # システム名　ポートフォリオ system_name
    system_name = models.CharField(
        verbose_name="システム名",
        max_length=20,
        blank=True,
        null=True
    )
    # システム概要　年間制作作品をまとめたサイト system_summary
    system_summary = models.TextField(
        verbose_name="システム概要",
        blank=True,
        null=True
    )
    # システムURL
    system_url = models.URLField(
        verbose_name="システムURL",
        blank=True,
        null=True
    )
    # サムネイル画像 system_thumbnail
    system_thumbnail = models.ImageField(
        verbose_name="サムネイル画像",
        upload_to= user_path,
        blank=True,
        null=True
    )
    # 制作背景　年間制作作品を多くの人に見てもらうため system_background
    system_background = models.TextField(
        verbose_name= "システム背景",
        blank=True,
        null=True
    )

    def __str__(self):
        return str(self.student)

portfolio2024/portfolio/forms.py
from django.forms import ModelForm
from .models import System

class Post(ModelForm):
    def __init__(self, *args, **kwargs):
        super(Post, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"

    class Meta:
        model = System
        fields = ['system_name', 'system_summary', 'system_url', 'system_thumbnail', 'system_background']

portfolio2024/portfolio/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView, UpdateView
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from .models import System
from .forms import Post

# Create your views here.
class IndexView(ListView):
    template_name = "index.html"
    model = System

class DetailView(DetailView):
    template_name = "detail.html"
    model = System

@method_decorator(login_required, name='dispatch')
class PostView(UpdateView):
    model = System
    form_class = Post
    template_name = "post.html"

    success_url = reverse_lazy('portfolio:index')
    def form_valid(self, form):
        postdata = form.save(commit=False)
        postdata.user = self.request.user
        postdata.save()
        return super().form_valid(form)

portfolio2024/portfolio/templates/base.html
{% load django_bootstrap5 %}
{% load static %}

<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.84.0">
  <title>福岡情報ITクリエイター専門学校_年間制作作品集</title>
  {% bootstrap_css %}
  {% bootstrap_javascript %}
  
</head>

<body>
  <header>
    <div class="bg-dark" id="navbarHeader">
      <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
          <a href="{% url 'portfolio:index' %}" class="navbar-brand">
            <strong>福岡情報ITクリエイター専門学校_年間制作作品集</strong>
          </a>
          {% if user.is_authenticated %}
          <a class="btn btn-light" href="{% url 'portfolio:post' user.pk   %}">システム編集</a>
          {% else %}
          <a class="btn btn-light" href="{% url 'portfolio:login' %}">学生ログイン</a>
          {% endif %}
        </div>
      </div>
    </div>
    </div>
    </div>
  </header>

  <main>
  {% block contents %}{% endblock %}
  </main>

  <footer class="text-muted py-5">
    <div class="container">
      <p class="float-end mb-1">
        <a href="#">Back to top</a>
      </p>
    </div>
  </footer>
</body>

</html>

portfolio2024/portfolio/templates/detail.html
{% extends 'base.html' %}

{% load static %}

{% block contents %}
  <div class="container">
  <ul class="list-group">
    <li class="list-group-item">氏名:{{object.student.username}}</li>
    <li class="list-group-item">システム名:{{object.system_name}}</li>
    <li class="list-group-item" style="white-space: pre-wrap;">システム概要:<br>{{object.system_summary}}</li>
    <li class="list-group-item">システムURL:<a href={{object.system_url}}>{{object.system_url}}</a></li>
    <li class="list-group-item" style="white-space: pre-wrap;">創意工夫した内容:<br>{{object.system_background}}</li>
  </ul>
    {% if object.system_thumbnail %}
      <img src="{{object.system_thumbnail.url}}" style="max-width: 50vw;border: solid;">
      <br>
    {% endif %}
    <a href="javascript:history.back();">戻る</a>
</div>
{% endblock %}

portfolio2024/portfolio/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block contents %}

<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h2>福岡情報ITクリエイター専門学校<br>年間制作作品集</h1>
    </div>
  </div>
</section>

<div class="album py-5 bg-light">
  <div class="container">
    
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      {% for record in object_list %}

      <div class="col" style="padding-bottom: 1rem;">
        <div class="card shadow-sm">

          {% if record.system_thumbnail %}
          <img src="{{ record.system_thumbnail.url }}" alt="サムネイル画像" class="bd-placeholder-img card-img-top" width="100%" height="225" style="aspect-ratio: 16 / 9;">
          {% else %}
          <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg"
            role="img" aria-label="Placeholder: No Image" preserveAspectRatio="xMidYMid slice" focusable="false">
            <title>Placeholder</title>
            <rect width="100%" height="100%" fill="#55595c" /><text x="50%" y="50%" fill="#eceeef" dy=".3em">No
              Image</text>
          </svg>
          {% endif %}

          <div class="card-body">
            <p class="card-text">{{record.student.student_no}}</p>
            <h5 class="card-text">{{record.student.username}}</h5>

            {% if record.system_name %}
            <h5 class="card-text">{{record.system_name}}</h5>
            {% else %}
            <h5 class="card-text">システム未提出</h5>
            {% endif %}

            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">

                {% if record.system_url %}
                <button type="button" class="btn btn-sm btn-outline-secondary"
                  onclick="location.href='{{record.system_url}}'">サンプルサイト</button>
                {% else %}
                <button type="button" class="btn btn-sm btn-outline-secondary" disabled>サンプルサイト</button>
                {% endif %}

                {% if record.system_summary %}
                <button type="button" class="btn btn-sm btn-outline-secondary"
                  onclick="location.href='{% url 'portfolio:detail' record.student_id %}'">詳細情報</button>
                {% else %}
                <button type="button" class="btn btn-sm btn-outline-secondary" disabled>詳細情報</button>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
      
      {% endfor %}
    </div>
  </div>
</div>

</main>
{% endblock %}

portfolio2024/portfolio/templates/login.html
{% load django_bootstrap5 %}
{% load static %}

<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.84.0">
  <title>福岡情報ITクリエイター専門学校_年間制作作品集</title>
  {% bootstrap_css %}
  {% bootstrap_javascript %}

</head>

<body class="text-center">
  <div class="container">
    <main class="form-signin">
      <!-- ユーザー名とパスワードが一致しない場合のメッセージ -->
      {% if form.errors %}
      <p style="color: red">学生番号とパスワードが一致しません。</p>
      {% endif %}
      <!-- ログインのフォームを配置 -->
      <form method="post">
        {% csrf_token %}
        <h1 class="h3 mb-3 fw-normal">学生ログイン</h1>
        <!--
        <div class="form-floating">～</div>の2つのブロックを削除して
        以下に書き換え
        -->
        <!-- Usernameのラベル(非表示) -->
        <label for="Username" class="visually-hidden">
          User name</label>
        <!-- usernameの<input>タグを出力-->
        <!-- name属性の値はLoginViewで定義されているフィールド名username -->
        <input type="text" name="username" id="id_username" maxlength="150" autocapitalize="none"
          autocomplete="username" class="form-control" placeholder="学生番号" required autofocus>
        <!-- Passwordのラベル(非表示) -->
        <label for="Password" class="visually-hidden">
          Password</label>
        <!-- passwordの<input>タグを出力-->
        <!-- name属性の値はLoginViewで定義されているフィールド名password -->
        <input type="password" name="password" id="id_password" autocomplete="current-password" class="form-control"
          placeholder="生年月日8ケタ" required autofocus>

        <!-- <button>～</button>を書き換えてログインボタンを配置 -->
        <input class="w-100 btn btn-lg btn-primary" type="submit" value="ログイン">


        <!-- ログイン直後のリダイレクト先(トップページ)のURLパターンを設定 -->
        <input type="hidden" name="next" value="{% url 'portfolio:index' %}">
      </form>
      <a class="btn btn-secondary" href="javascript:history.back();">戻る</a>
    </main>
  </div>
</body>

</html>

portfolio2024/portfolio/templates/post.html
{% extends 'base.html' %}

{% load static %}

{% block contents %}
<div class="container">
  <div class="col-md-7 col-lg-8">
    <h4 class="mb-3">制作システム更新</h4>

    <form method=post class="form-group" enctype="multipart/form-data">
      <div class="form-group">
        {% csrf_token %}
        {{form}}
        <button class="btn btn-primary submit" type="submit">更新する</button>
    </form>

  </div>
  {% endblock %}